LEST-26 - Implemented more equality matchers
TAServers/lest pull request #1
Opened 2023-02-13 01:35 UTC by yogwoggf

Overview:
- Implemented the scaffolds for the new equality matchers.
- Added unit tests for `equality.lua`. 100% code coverage. (toBeNil is an alias, so it isn't in the tests.)

## Questions
- Are these unit tests in good style?
- `toBeInstanceOf` is unclear. Should it act like JavaScript, scanning for multiple parent classes? Or.. should it just scan for the immediate parent class (**currently implemented as such**). In Lua, multiple inheritance is implemented in many ways. I don't think we could offer this functionality because the user's project might have implemented it differently.

This PR will remain as a draft until the questions are answered.

2023-02-13 01:37 UTC, yogwoggf commented
Forgot to mention, all tests are passing on my end.

2023-02-13 03:18 UTC, yogwoggf commented
Wait.. wouldn't we need to use Lua assertions for all of the matcher unit tests? Let me know what you want to do with the `matcherPassed` utility. Perhaps it should be split into another file?

2023-02-13 08:53 UTC, Derpius requested changes

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.lua
> +		pass = deepEqual(getmetatable(received), metatable),
This shouldn’t use deep equality

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +-- basic lua assertions to verify matcher behavior.
Useless comment

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +				expect(2).toBe(2)
This is testing too much (in fact it’s a full integration test of the entire expect system + matcher).

And assuming this is *actually* what we wanted (which it isn’t in this case), there’s absolutely no reason to use this assert. The matcher will pass the test if it passes and will fail it if it fails, rendering this code redundant.


What these tests should actually do is import the matchers directly, then assert `pass` and the `message` properties of the returned result. It should do this for both normal and inverted modes.

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +		it("should pass on deep equality", function()
Neither this nor the below test perform equality tests on a deep value, only a shallow table

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +				-- FYI: 1 and 0 are both truthy in Lua unlike other languages.
Useless comment

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +				expect("").toBeTruthy()
If you’re going to test with multiple types, why not use an exhaustive set?

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +				expect("").toBeFalsy()
If you’re going to test with multiple types, why not use an exhaustive set?

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.test.lua
> +		end
This is a lot more code than actually needed for a test like this.

```lua
local Class = {}
local instance = setmetatable({}, Class)
```

2023-02-13 08:53 UTC, Derpius commented on src/matchers/equality.lua
> +	return {
Could you add an assert for the type of `metatable` here?

Note that this isn’t done in other matchers yet but needs to be added.

2023-02-13 08:57 UTC, Derpius commented
toBeInstance should just do a direct reference equality check between the metatable of received and the passed metatable.

There is no need to worry about inheritance as Lua doesn’t really have it. If the user of the testing framework needs to repeatedly test their own system for inheritance, they can write a custom matcher (or will be able to in the final product)

2023-02-13 12:26 UTC, Derpius commented
Would probably be best to wait for me to do one of the other suite of matchers, so you can use that as reference

2023-02-14 02:56 UTC, yogwoggf commented
What the fuck

2023-02-14 02:56 UTC, yogwoggf commented
Mmmmmmmmmmmmmm lua 5.1 doesn't coerce the table to a string....... so glad we have these tests in the CI now, should've used `prettyValue` anyways

2023-02-14 03:01 UTC, yogwoggf commented
Ok, all tests pass now. The new commits introduce an actual fucken unit test suite for `equality.lua` and adds the requested `assert` for `toBeInstanceOf`.

2023-02-14 11:32 UTC, Derpius approved these changes

2023-02-14 20:24 UTC, merged